# Generated by Django 4.2.9 on 2024-04-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dish_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='ID_card',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='business_license/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='business_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='food_safty_cert',
            field=models.ImageField(blank=True, null=True, upload_to='safty_cert/'),
        ),
        migrations.AddField(
            model_name='provider',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
