# Generated by Django 4.2.9 on 2024-04-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_menu_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='toping/')),
                ('price', models.IntegerField(default=0)),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.dish')),
            ],
            options={
                'verbose_name': 'Toping',
                'verbose_name_plural': 'Toping',
            },
        ),
    ]
