# Generated by Django 4.2.9 on 2024-04-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdish',
            name='status',
            field=models.CharField(choices=[('Đang chờ xử lý', 'Đang chờ xử lý'), ('Đã tiếp nhận', 'Đã tiếp nhận'), ('Đang giao', 'Đang giao'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Đang chờ xử lý', max_length=31),
        ),
    ]
