# Generated by Django 4.2.9 on 2024-04-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_review_review_type_alter_orderdish_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_type',
        ),
    ]
