# Generated by Django 4.2.9 on 2024-04-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_review_review_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
