# Generated by Django 4.2.11 on 2024-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Toping',
        ),
    ]
