# Generated by Django 4.2.11 on 2024-04-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_cart_note_delete_toping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderdish',
            options={},
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orderdish',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ xử lý', 'Đang chờ xử lý'), ('Đã tiếp nhận', 'Đã tiếp nhận'), ('Đang giao', 'Đang giao'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Đang chờ xử lý', max_length=31),
        ),
    ]
