# Generated by Django 4.2.11 on 2024-04-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_order_options_alter_orderdish_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdish',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
