# Generated by Django 4.2.11 on 2024-04-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_provider_id_card_remove_provider_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='old_price',
        ),
    ]
