# Generated by Django 4.2.11 on 2024-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_dish_distance_remove_dish_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'customer'), (2, 'provider')], default=1, max_length=15),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
